rabbit:
  image: "rabbitmq:3-management"
  hostname: "rabbit"
  environment:
    RABBITMQ_DEFAULT_USER: "admin"
    RABBITMQ_DEFAULT_PASS: "admin"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq"

service:
  build: .
  container_name: template
  environment:
    RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@rabbit"
    RABBITMQ_QUEUE: "test.queue"
  links:
    - rabbit
